CALLDIR=$1
OUTPUTDIR=$CALLDIR/subsampling/
SCRIPTDIR=$2


CONTROL=ICC21_control.CGmap
CONTROL_CONTEXT_ALL="CG+CHG+CHH.$CONTROL"

LR2=ICC26_LR5007.CGmap
LR2_CONTEXT_ALL="CG+CHG+CHH.$LR2"


qsub -S /bin/bash $SCRIPTDIR/subsampleAllCGmap.sh $CALLDIR/$CONTROL $OUTPUTDIR/$CONTROL_CONTEXT_ALL
qsub -S /bin/bash $SCRIPTDIR/subsampleAllCGmap.sh $CALLDIR/$LR2 $OUTPUTDIR/$LR2_CONTEXT_ALL
	

